# Generated by Django 4.1.1 on 2022-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=30, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('In stock', 'In Stock'), ('On order', 'On Order'), ('Expected to arrive', 'Expected To Arrive'), ('Not available', 'Not Available'), ('Not produced', 'Not Produced')], default='Expected to arrive', max_length=30, verbose_name='state'),
        ),
    ]
