# Generated by Django 4.1.1 on 2022-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_price_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\zarub\\Documents\\projects\\twrk-back\\images', verbose_name='image'),
        ),
    ]
